### ISSUE TITLE
Removal of small-caps for RFC2119 keywords

### ISSUE THREAD

**Issue by anarchivist** [w3c/respec#1109]
I noticed in reviewing an editor's draft of a spec that formatting of RFC2119 keywords changed, which looks like it was introduced in f628857df8fda2768370a7182754b1117cb974d0. Can you clarify why this change was made?

**Comment by marcoscaceres** [comment]
People have told me it's unnecessarily distracting and it's becoming the norm to not capitalize RFC2119 words in web specs. For example, [HTML](https://www.w3.org/TR/html52/infrastructure.html).

**Comment by anarchivist** [comment]
It seems like it was a sudden change - was there discussion documented anywhere about this?

**Comment by marcoscaceres** [comment]
@anarchivist, sorry, I should have provided more background. The wider context is that we are trying to deprecate ReSpec's stylesheet #748 because we want a consistent look across w3c specs (and leave it to W3C and other orgs to define how specs should be styled). 

People have various opinions about how certain things should be styled (e.g., https://github.com/w3c/browser-payment-api/issues/377). And, as I pointed out, HTML and other specs are also moving away from upper-casing these words. 

There hasn't been much formal discussion - just a year over year grumble over things.  

Having said that, if you feel you want lower-caps for RFC2119 keywords, you can simply just add https://github.com/w3c/respec/commit/f628857df8fda2768370a7182754b1117cb974d0 back to your spec's CSS inline. If you feel strongly that RFC2119 keywords MUST be capitalized (as per RFC2119) - I suggest that might be something to raise with the W3C: https://github.com/w3c/tr-design/
 
Similarly, if you are using ReSpec with another organization, we'd like to encourage folks to take control of their own styles.

**Comment by marcoscaceres** [comment]
Closing for now. @anarchivist, please feel free to reopen if you feel this needs further discussion.
