### ISSUE TITLE
CSS validator complains of @support

### ISSUE THREAD

**Issue by palemieux** [w3c/respec#1163]
https://jigsaw.w3.org/css-validator/validator?uri=https://www.w3.org/TR/2017/WD-ttml-imsc1.0.1-20170323/

_Sorry, the at-rule @supports is not implemented._

Probably introduced by https://github.com/w3c/respec/issues/1150

**Comment by marcoscaceres** [comment]
Hmm... ok, will try to think of something. 

@sideshowbarker, what are the odds of updating the CSS validator?

**Comment by sideshowbarker** [comment]
The CSS validator is actively maintained—not by me, but if you file an issue at https://github.com/w3c/css-validator/issues I expect you will get a response

**Comment by marcoscaceres** [comment]
@sideshowbarker thanks! filed https://github.com/w3c/css-validator/issues/71

**Comment by sandhawke** [comment]
I wonder if it'd be possible to keep respec from getting ahead of W3C pubrules/validators?   Like, consider the output generating a proper publication as a requirement before releasing changes to respec?    I'd rather not have to hunt down issues like this @support one just to do a publication, and I expect I'm not alone in that.

**Comment by marcoscaceres** [comment]
Feel your pain. I'll see if I can remove the @ supports.

**Comment by sandhawke** [comment]
Thanks.    There are two other css issues at the moment, from the css validator on respec output, which I haven't tracked down:

 .respec-save-button:link 	Property justify-self doesn't exist : stretch
 .respec-button-copy-paste 	Property user-select doesn't exist : none

**Comment by anssiko** [comment]
As noted by @sandhawke, the '[justify-self][1]' and '[user-select][2]' properties that were added to ReSpec CSS some days ago now cause all the HTML snapshots produced with ReSpec fail the CSS validator step in the Pubrules Checker. See an [example of such a CSS validator failure][3].

@marcoscaceres, a possible fix would be to include only the minimum CSS in the HTML snapshot that also passes CSS validator, and remove the problematic CSS required only by the ReSpec pill and its associated UI, including the redundant github.com styles. In addition, I suggest you consider adding a CSS validator step to Travis CI build as a future mitigation mechanism.

@sandhawke, if you're in a hurry with your publication (and are not using Echidna), you can try this: manually remove [this ReSpec-generated CSS][4] from the generated HTML snapshot to make it pass CSS validator. This workaround only works if you're not using Echidna for publishing, since it requires you to apply this patch manually to the generated HTML snapshot. It worked for me when I was preparing the above-mentioned spec for CR publication.

[1]: https://drafts.csswg.org/css-align/#justify-self-property
[2]: https://drafts.csswg.org/css-ui-4/#propdef-user-select
[3]: https://www.w3.org/pubrules/?url=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%253A%252F%252Frawgit.com%252Fw3c%252Fmediacapture-depth%252FTR%252Findex.html%253FspecStatus%253DWD%253BshortName%253Dmediacapture-depth&profile=WD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004
[4]: https://github.com/w3c/html-media-capture/commit/7002095f54862a2efa58afc5a1a4e34d09ae6f36

**Comment by marcoscaceres** [comment]
So yeah, my plan is to split the UI's CSS into a separate file (which will get removed when spec generation happens).
