### ISSUE TITLE
Respec is errantly subtracting 1 day from previousPublishDate and publishDate

### ISSUE THREAD

**Issue by tantek** [w3c/respec#1272]
Example: https://tantek.github.io/post-type-discovery/index-wd-src.html (respec generated)

Opened in Firefox 53.0.3.

1. Respec is screwing up previousPublishDate

View source

it has:         previousPublishDate: "2017-03-01", 
(which is correct)

the visible page shows (and links to)

"
Previous version:
https://www.w3.org/TR/2017/WD-post-type-discovery-20170228/
"

Why is respec subtracting a day from previousPublishDate 2017-03-01 to generate that link to 20170228?

2. Respec is screwing up publishDate

View source again

it has:        publishDate: "2017-06-14",

the visible page shows (and links to) in numerous places:

"
W3C Working Draft 13 June 2017
"

"
This version:
https://www.w3.org/TR/2017/WD-post-type-discovery-20170613/
"

etc.

Why is respec subtracting a day from previousPublishDate 2017-06-14 to generate 13 June 2017 and 20170613?

**Comment by dissolve** [comment]
This is happening to me as well.  I had to adjust the html after saving a static html version.

**Comment by marcoscaceres** [comment]
@tantek, @dissolve, could you kindly confirm you are using ReSpec 14.0.2? You can do this by clicking on the ReSpec pill, and selection "About ReSpec..." (or type `window.respecVersion` in the dev console). If you are still on an old ReSpec, give it a "shift-refresh".

I introduced that bug by accident a few days ago, but I thought [I'd fixed it](https://github.com/w3c/respec/pull/1259). It happens because JavaScript `Date.parse()` parses in UTC instead of the system timezone. Yay, JS `Date()` object 👍

**Comment by dissolve** [comment]
Tested just now (9:20 AM Eastern), And Its still doing it, on 14.0.4
source has
`publishDate: "2017-06-14",`

resulting file has 
<pre>
      "publishDate": "2017-06-14", 
...
      "publishISODate": "2017-06-14T00:00:00.000Z",
      "generatedSubtitle": "Working Draft 13 June 2017"
...
&lt;h2 id="w3c-working-draft-13-june-2017"&gt;&lt;abbr title="World Wide Web Consortium"&gt;W3C&lt;/abbr&gt; Working Draft &lt;time property="dcterms:issued" class="dt-published" datetime="2017-06-13"&gt;13 June 2017&lt;/time&gt;&lt;/h2&gt;
...
      &lt;dd&gt;&lt;a class="u-url" href="https://www.w3.org/TR/2017/WD-jf2-20170613/"&gt;https://www.w3.org/TR/2017/WD-jf2-20170613/&lt;/a&gt;&lt;/dd&gt;
</pre>

**Comment by marcoscaceres** [comment]
@dissolve very strange... will see if I can figure out what's going on.

**Comment by marcoscaceres** [comment]
(if you need a temporary work around, you can use a JS object)

```JS
"publishDate": new Date("2017-06-14"),
```

**Comment by marcoscaceres** [comment]
Actually, probably safer to do:

```JS
  "publishDate": new Date(2017,6,14),
```

Will try to figure out why it's converting to UTC on output.

**Comment by marcoscaceres** [comment]
I decided to treat everything as UTC - otherwise, it turns into timezone insanity (and should stop strange things from happening, because dates are given for everything, so they are explicit ISO dates, which are UTC). Sending a PR.

**Comment by marcoscaceres** [comment]
@dissolve, could you please let me know if it's ok now 🤞

**Comment by marcoscaceres** [comment]
(actually, give it a minute if you just saw this... currently being released... version should be 14.0.5)

**Comment by dissolve** [comment]
Yikes, this actually made it worse for me.
I'm now on 14.0.6
tested this morning at 09:15am EDT
source file:
`         publishDate: "2017-06-16",`

resulting in 

<pre>
      "publishDate": "2017-06-16",
...
      "publishISODate": "2017-06-15T00:00:00.000Z",
      "generatedSubtitle": "Working Draft 14 June 2017"
...
    &lt;h2 id="w3c-working-draft-14-june-2017"&gt;&lt;abbr title="World Wide Web Consortium"&gt;W3C&lt;/abbr&gt; Working Draft &lt;time property="dcterms:issued" class="dt-published" datetime="2017-06-14"&gt;14 June 2017&lt;/time&gt;&lt;/h2&gt;
    &lt;dl&gt;
      &lt;dt&gt;This version:&lt;/dt&gt;
      &lt;dd&gt;&lt;a class="u-url" href="https://www.w3.org/TR/2017/WD-jf2-20170614/"&gt;https://www.w3.org/TR/2017/WD-jf2-20170614/&lt;/a&gt;&lt;/dd&gt;

</pre>

**Comment by dissolve** [comment]
So, i have explored a little bit further.
in src/w3c/headers.js 
```
  conf.publishDate = new Date(                                                                                                                     
    ISODate.format(                                                                                                                                
      new Date(conf.publishDate ? conf.publishDate : doc.lastModified)                                                                             
    )                                                                                                                                              
  );  
```
changing this to just
```
  conf.publishDate =  new Date(conf.publishDate ? conf.publishDate : doc.lastModified);                                                                           
```
fixes the issue, IF I do not set a publishDate in the source document.
If I do, it assumes that the set value is UTC, when it hits this line, 
it changes outputs it in localtime, and we get 
'2017-06-16'
changed to 'Thu Jun 15 2017 20:00:00 GMT-0400 (EDT)'

I feel like the correct way to solve the issue is "if there is no timezone given in the 'publishDate' field, assume timezone is UTC, but not quite sure how to best implement that.

However, even fixing that (in a temporary and hacky way).

W3CDate needs to have timeZone: 'UTC' set in the options to correct the generateSubtitle field
concatDate ends up giving the previous day,

at about this point i decided to give up and wait for more input as i just keep going farther and farther down the rabbit hole.

**Comment by dissolve** [comment]
actually, setting timeZone in ISODate fixes the rest of them too
export const ISODate = new Intl.DateTimeFormat(["en-ca-iso8601"], {
  timeZone: "UTC",

So its just a matter of forcing the timezone to be UTC for set values of publishDate where the timezone is not set.

**Comment by dissolve** [comment]
ignore all I said before... created a PR that solves the issues for me, everything gets output with the correct date whether publishDate is set or not.
