### ISSUE TITLE
Stable Release URL

### ISSUE THREAD

**Issue by awoods** [w3c/respec#1301]
Is there a stable release URL that we can use to avoid unexpected breaking changes?
..or is the suggestion to host a local copy?
http://fedora.info/spec/

**Comment by marcoscaceres** [comment]
Not on the w3c version - it's always bleeding edge (because we like to live dangerously🔥). If you want to host your own, it's easy to build a particular version. 

Just clone the repo, and then:

```Bash
npm install
npm run build
```

The built bundle ends up in `builds/`, which you can host on your own server. 

You can then pull and test against your own specs.  

You also have the option of hosting your own fork on github - with a custom profile. Geonovum does that:
https://github.com/Geonovum/respec

They pull in updates periodically from our repo.

**Comment by marcoscaceres** [comment]
(note the you can even serve your own version off github pages, which means you don't need to worry about hosting or anything)

Also, if stuff breaks, please file bugs and let us know. Breaking stuff is no fun, obviously, so helping us better test things really helps.

**Comment by awoods** [comment]
Thanks, @marcoscaceres
