### ISSUE TITLE
Serve save-html.js with a javascript mime type

### ISSUE THREAD

**Issue by equalsJeffH** [w3c/respec#1439]
seems like the `save-html.js` respec feature is not working (for me at least) due to `https://raw.githubusercontent.com/darobin/respec/gh-pages/js/ui/save-html.js` serving a `X-Content-Type-Options: nosniff` response header field, tho not also declaring the returned content type via a javascript mime type.

From Firefox 56.0.2: 
```
The resource from “https://raw.githubusercontent.com/darobin/respec/gh-pages/js/ui/save-html.js” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).[Learn More]  fido-client-to-authenticator-protocol-master-e0a6d48-respec.html
Loading failed for the <script> with source “https://raw.github.com/darobin/respec/gh-pages/js/ui/save-html.js”.  fido-client-to-authenticator-protocol-master-e0a6d48-respec.html:1
Error: Script error for: ui/save-html
http://requirejs.org/docs/errors.html#scripterror
```

Safari 11:
```
Did not load script at 'https://raw.github.com/darobin/respec/gh-pages/js/ui/save-html.js' because non script MIME types are not allowed when 'X-Content-Type: nosniff' is given.
```

**Comment by marcoscaceres** [comment]
@equalsJeffH, do you have a link to the actual spec? Just by looking, you shouldn't be able to load ReSpec off Github like that, as it's really supposed to be loaded up bundled. Regardless, it would be interesting to see what you are trying to do and work out why it's failing.

**Comment by equalsJeffH** [comment]
the spec is in a private repo unfortunately.  but in any case, your reply is hinting that our respec snapshot is horked :-/
thanks.

**Comment by marcoscaceres** [comment]
@equalsJeffH, because everything does work as expected when served from localhost, my suspicion is that those Github-sent HTTP headers you listed are what is causing things to fail. Hosting ReSpec somewhere else might work - but note that loading the modules independently can have a performance penalty (at least on first load, and if the cache is not tuned just right).

Best of luck with it! If you do eventually make things public, would be super interested to see what you are doing. Eventually, I'd like to serve all modules independently too, and then I can update ReSpec's module's incrementally, and even hot-update them!
