### ISSUE TITLE
Back to Top button doesn't work

### ISSUE THREAD

**Issue by OrionStar25** [w3c/respec#1545]
eg :- https://www.w3.org/TR/payment-request/
The arrow button used for navigating to the top hasn't been assigned any top link in any of the specs.

**Comment by marcoscaceres** [comment]
@OrionStar25, could you clarify a little bit more? I'm having trouble finding the "Back to Top" button you mentioned. If possible, please include a screenshot.

**Comment by himanish-star** [comment]
![image](https://user-images.githubusercontent.com/30361728/36880692-0d109514-1df0-11e8-96f0-464becfaaee7.png)

@marcoscaceres this is the `back to top` button which is not functioning. @OrionStar25 Am I right?

**Comment by marcoscaceres** [comment]
Ah, got it! ok, it actually _is_ functioning... but it's kinda useless because it links back to the "#toc", which is being displayed in the side panel. If you "collapse side bar", and click it, you can see it working. 

But technically, @OrionStar25 is correct that this is confusing. I'll just note that this is something that's being added by the W3C's "inject.js" script, so it's technically not a ReSpec issue... but, we can definitely bring this issue to the W3C's attention so they can fix it on their side. 

The project for that is: http://github.com/w3c/tr-design

**Comment by himanish-star** [comment]
> it actually is functioning

:+1:

**Comment by marcoscaceres** [comment]
Actually, I lied, it's a ReSpec bug: 
https://github.com/w3c/respec/blob/develop/src/core/structure.js#L147

@OrionStar25, you want to fix this?

**Comment by OrionStar25** [comment]
Yeah! I'll work on this! :D

**Comment by OrionStar25** [comment]
@marcoscaceres So we want the TOC when the side panel exists and top of the spec when its been collapsed. Or we could just bring it to the top of the spec in both cases as TOC mostly is concise enough (?)

**Comment by marcoscaceres** [comment]
No, let’s make it simpler. Just take the reader back to the very top of the document. Check if you can either hook into the #head or change the scroll position.

**Comment by OrionStar25** [comment]
PR sent!
