### ISSUE TITLE
Test the dropdown for caniuse feature

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#1642]
In `spec/core/caniuse-spec.js` (line 116), the `firefoxButton.focus()` is not working. Need to figure out an alternative (or make it work).

Files for feat/caniuse: `src/core/caniuse.js`, `js/core/css/caniuse.css`, `spec/core/caniuse-spec.js` 

~It is currently a part of https://github.com/w3c/respec/pull/1627~

**Comment by markasoftware** [comment]
It seems that triggering pseudoclasses from JS is impossible by design. The most reasonable way to test this, then, would probably be to add another class to https://github.com/w3c/respec/blob/24bf82b40e2e2ccb9efccc04390264b25252db77/assets/caniuse.css#L105 which is only used for testing. The test would call `firefoxButton.classList.add('whatever')` instead of `firefoxButton.focus()`. Personally, I don't think this is even worth testing -- the styles are written right there in the CSS.

**Comment by marcoscaceres** [comment]
Agree, not worth testing.

**Comment by sidvishnoi** [comment]
I found a _fun_ thing related to focus though. When the tab loses focus, `button.focus()` starts working 🤷‍♂️ 
Have a look https://streamable.com/f5lnc

**Comment by markasoftware** [comment]
To add to @sidvishnoi 's little discovery, it's actually even simpler: Running `button.focus()` in devtools then clicking anywhere on the spec page will open the dropdown! It seems that `focus()` actually can trigger the `:focus` pseudoclass (at least in Firefox), but the page must have focus too. This is probably the problem preventing it from working in tests: The frame containing the tests is not in focus.

**Comment by marcoscaceres** [comment]
I think to test this stuff properly we would need puppeteer.
