### ISSUE TITLE
Recent ReSpec update broke WebIDL parsing for WoT defintitions

### ISSUE THREAD

**Issue by danielpeintner** [w3c/respec#1728]
## Important info

* URL to affected spec: https://w3c.github.io/wot-scripting-api/
* ReSpec version: 22.1.0

## Description of problem

What happened (e.g., it crashed)?: 

Many WebIDL defintitions cause parsing issues. For example `interface WoT`
https://w3c.github.io/wot-scripting-api/#the-wot-object

But what I was expecting?:

The following used to parse just fine and now complains about many things

```
    <pre class="idl">
      // [SecureContext]
      // [NamespaceObject]
      interface WoT {
        Observable&lt;ThingDescription&gt; discover(optional ThingFilter filter);
        Promise&lt;ThingDescription&gt; fetch(USVString url);
        ConsumedThing consume(ThingDescription td);
        ExposedThing produce(ThingModel model);
        Promise&lt;void&gt; register(USVString directory, ExposedThing thing);
        Promise&lt;void&gt; unregister(USVString directory, ExposedThing thing);
      };
      typedef dictionaryThingTemplate;
      typedef USVString ThingDescription;
      typedef (ThingTemplate or ThingDescription or ConsumedThing) ThingModel;
    </pre>
```

Optional, steps to reproduce:
 1. Sometimes `&lt;` in other cases `<` needed

```
        Observable<ThingDescription> discover(optional ThingFilter filter);
        Promise&lt;ThingDescription&gt; fetch(USVString url);
```

Promise requires `&lt;` while  Observable `<` ?

2. type dictionary not allowed anymore

`typedef object ThingTemplate; // type dictionary not allowed anymore?`

3. Maybe some more issues...

**Comment by marcoscaceres** [comment]
Thanks for letting us know! Will fix today.

**Comment by marcoscaceres** [comment]
@danielpeintner thanks for providing the test case to reproduce (hi also @zolkis, as I see he is editing). 

Looking at your IDL, the problem is that the IDL itself is invalid. Although you define the `Observable` interface in you spec, WebIDL forbids arbitrary interfaces from being used as a generic (only certain things, like `Promises`, can use that syntax).

The `typedef`s are also invalid. If you look at the error, it states that the name is missing for those too. 

There are also a bunch of invalid things further down in your spec... like `attribute maplike` is invalid: an interface can be "maplike", but not an attribute.

Hope that helps!

**Comment by zolkis** [comment]
@marcoscaceres thanks for the review. Looks like now we get better checking on the WebIDL and finally need to fix our stuff. 

The intent about `maplike` was to express a collection of named properties in an object as property bag instead of specifying arrays. We could just say `object` or `any` or `Dictionary` and specify the types in prose. Just like we need to do with the type of values provided by the Observables we use.

To avoid being lost in translation, perhaps we should directly use TypeScript in the WoT Scripting spec, as the Node.js implementation is using that and there is no browser implementation at the moment.

**Comment by marcoscaceres** [comment]
> The intent about maplike was to express a collection of named properties in an object as property bag instead of specifying arrays. We could just say object or any or Dictionary and specify the types in prose. Just like we need to do with the type of values provided by the Observables we use.

Got it. You might need to just define an interface for that:

```JS 
interface BagOfFunThings {
  maplike<DOMString, any>;
}

interface SomeOtherInterface {
  readonly attribute BagOfFunThings things;
}
```

Maybe take a look at how URLQueryParams interface works. This seems quite similar.
