### ISSUE TITLE
Change the way references are defined as informative or normative

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#1754]
The following modified syntax shall be used for defined whether an inline spec reference is informative or normative:
- `[[!spec]]`: normative.
- `[[?spec]]`: informative.
- `[[spec]]`: decided based on parent. If defined in a non-normative section, then informative, else normative.

**Comment by marcoscaceres** [comment]
@andrea-peregol,  could you try `class="informative"` on the body:

```HTML
<body class="informative">
```

That should probably do it... then you won't need `class=informative` on all the `<section>`s.

**Comment by andrea-perego** [comment]
Thanks, @marcoscaceres , we will try it out. However, it is still unclear to me why the default is "normative".

**Comment by marcoscaceres** [comment]
> Thanks, @marcoscaceres , we will try it out. However, it is still unclear to me why the default is "normative".

That's a good question... generally, most docs are specs that are supposed to be REC Track, so we defaulted to everything being Normative. 

We might need to change that so that specific kinds of documents default to non-normative, but I've not yet worked out a good way of doing that. I'm open to suggestions tho.

**Comment by marcoscaceres** [comment]
Actually, what we could do is if the document has no `<section id="conformance">`, then it's treated as informative. That might solve it.

**Comment by andrea-perego** [comment]
Thanks, @marcoscaceres , this clarifies things.

Just thinking aloud, but another option could be to check in config.js whether a doc is or not on REC track to decide which should be the default. Said that, in my experience, if there are normative sections, people take care of specifying this explicitly - also because there will be informative sections as well. So, I wonder whether it would be better (and safer) to set as default "informative" in all cases.

**Comment by marcoscaceres** [comment]
> Just thinking aloud, but another option could be to check in config.js whether a doc is or not on REC track to decide which should be the default. 

I thought the same... then I remembered:
http://github.com/w3c/payment-method-basic-card

(Not on Rec Track, but lots of Normative requirements... don't get me started :))

> So, I wonder whether it would be better (and safer) to set as default "informative" in all cases.

For all specs, I think the declaration of the `<section id=conformance>` actually solves this explicitly, because it states: 

>   As well as sections marked as non-normative, all authoring guidelines,
      diagrams, examples, and notes in this specification are non-normative.
      Everything else in this specification is normative.

So, by including ` id=conformance` the author is opting into Normative by default. 

Does that sound right?

**Comment by andrea-perego** [comment]
+1 from me

**Comment by marcoscaceres** [comment]
Ok cool. Filing a bug now. Will cc you and get this fixed ASAP.

**Comment by andrea-perego** [comment]
Thanks!

**Comment by marcoscaceres** [comment]
We have a lot o students contributing to ReSpec at the moment, so I'll guide one of them to how to fix this for us. If you don't mind, it usually takes them 2-3 days (would probably take the core team a few mins to fix), but they gain a lot out of the experience. Hope the delay is ok. If you prefer not to wait, just do the `<body class="informative">` suggestion above, as fix will do exactly the same thing :)

**Comment by andrea-perego** [comment]
No problem.
