### ISSUE TITLE
improved UX: normative and informative references should link directly, to correspond to web best practices and user expectations

### ISSUE THREAD

**Issue by deborahgu** [w3c/respec#1820]
When users select a link in a W3C doc, they generally expect the behavior of the modern web: i.e. they expect that link to take them to the document that seems to be linked. The ReSpec behavior is to take the user instead to the references section, written like a print bibliography, which contains the link the user expected to see twice, once by title and once by URL, as if the bibliography were intended to be printed.

For anyone not skilled in reading W3C documents, this is an exceptionally confusing experience.

Building the `References` section from the normative and informative references should still happen, but the links themselves should go to the linked resource directly. There is no usability or informative purpose served by the intervening middle step; users know how to extract the information they need directly from the linked page.

**Comment by marcoscaceres** [comment]
We agree, which is why we have `data-cite`, which does precisely what you describe: links directly to another spec AND adds a reference to the bibliography. See example of using with `a` element: https://github.com/w3c/respec/wiki/data--cite

If there is some spec doing it incorrectly, I’d suggest fixing that spec. I’m happy to provide guidance, just ping 🛎.

**Comment by deborahgu** [comment]
Oh, thanks! And yes, every single respec doc I'm contributing to in any way is not doing this correctly (or at least, not consistently).  I will contact all the editors for those documents.
