### ISSUE TITLE
Get a way to exclude certain IDL blocks from IDL index

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1880]
Specs sometimes have IDLs only to give examples/templates but not for actual implementations.

https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-_camel_cased_attribute

https://w3c.github.io/mediacapture-main/#interface-definition

Bikeshed has a way to exclude them from IDL index [by marking it as `extract`](https://tabatkins.github.io/bikeshed/#no-idl), but ReSpec has no equivalent feature.

**Comment by saschanaz** [comment]
The Media Capture and Streams spec does have some IDL types that won't ever be directly referenced by others. Maybe those should be marked as `.example`s, but currently the IDL Index would still collect them.

**Comment by marcoscaceres** [comment]
The Media Capture thing is weird... because `ConstrainablePattern` wants to be an abstract interface, and it theory is normative (in as far that it defines normative things). It just can't be implemented to do anything (i.e., it's a kind of editorial aid). 

So, I guess maybe we need an explicit "no-index" CSS class, but also exclude IDL that is non-normative. That would solve for both.
