### ISSUE TITLE
Refactor biblio-db with idb dependency

### ISSUE THREAD

**Issue by saschanaz** [w3c/respec#1955]
We now have `idb-keyval` so we probably want to use it there, as the current code is a mixture of Promises and callbacks.

**Comment by NJnisarg** [comment]
Hello, I am new to this project and am trying to contribute. Since this was marked as good first issue I was trying to understand it. Can you guide me to work on this?

What I understood is biblio-db is a module which stores the data related to some kind of references and it seems to be built on top of indexedDB API. If I am not wrong it has its own functions that work as wrappers to the lower level indexedDB API. And this issue is possibly trying to replace/modify this module with the package [idb-keyval](https://www.npmjs.com/package/idb-keyval) from nodejs/npm.

**Comment by saschanaz** [comment]
@NJnisarg Hello, welcome to ReSpec! 🎉 

Yes, this issue is to replace direct calls to raw IndexedDB API with the library `idb-keyval`. AFAIK most of the things should be straightforward for one who knows IDB well, but one of my concern is that `idb-keyval` is just a key-value store so it does not support `onupgradeneeded` event. Maybe we should upgrade to https://www.npmjs.com/package/idb for this.

Feel free to ask questions if you find any.

cc: @sidvishnoi who added the dependency 👍

**Comment by marcoscaceres** [comment]
@NJnisarg, just in case you haven't yet seen it, we have a dev guide to help people get started https://github.com/w3c/respec/wiki/Developers-Guide

**Comment by NJnisarg** [comment]
@marcoscaceres and @saschanaz Thanks! I have gone through the Developer Guide and am trying to work with what the issue suggests. I am understanding the codebase a little as of now and would like to take this up as my first issue. I would post questions that are relevant to the issue here. Thanks again and looking forward to contribute.

**Comment by sidvishnoi** [comment]
> Maybe we should upgrade to https://www.npmjs.com/package/idb for this.

Certainly if it helps. Presently, the `idb-keyval` is being used just in `core/xref` (and its tests) and it should be trivial to replace. I'll send a PR tomorrow for that.

**Comment by NJnisarg** [comment]
@sidvishnoi Hello, by the way I am trying to work on this biblio-db issue, do you mind if I continue and generate a PR in a few days? I might reach out for help.

**Comment by sidvishnoi** [comment]
@NJnisarg Sure feel free to ask wherever needed. Happy to help.
And yes, we can wait on this biblio-db PR, no hurries. I'll just set up the `idb` dependency so you can import and use it later (and I'll fix the usage in xref module).

**Comment by pradeepgangwar** [comment]
@sidvishnoi Is this issue solved? If not then I would like to take this up.

**Comment by aarondtaveras** [comment]
Hey everyone, I've been browsing through this project and I'm looking to contribute!

I see that this issue is still open and I'd like to take a crack at it if that's acceptable. I'll stay on this thread to keep asking any questions that I may have. Has there been any progress on this after setting up the `idb` dependency? Thank you, and I'm looking forward to helping out the team! 😄

**Comment by marcoscaceres** [comment]
@aarondtaveras, I think this is actually fixed, but #2154 needs some work if you’d like to help.

**Comment by aarondtaveras** [comment]
@marcoscaceres, I’d love to! #2154 is the PR for updating the `idb` version. Is updating the version to `4.0` what you’d like me to take a look at?

**Comment by marcoscaceres** [comment]
Yes please.

**Comment by sidvishnoi** [comment]
`biblio-db.js` still uses raw `indexedDB` instead of `idb`

**Comment by pradeepgangwar** [comment]
I guess this was fixed by #2191 . @marcoscaceres Does it require more work?

(I browse through issues and at some point of browsing/searching I find some merged PR 😆. Leaves me with a sad face xD)

**Comment by marcoscaceres** [comment]
Still open, but @Swapnilr1 is working on it.

@pradeepgangwar, will need to find another one for you.

**Comment by pradeepgangwar** [comment]
Yeah, no problem. I will look for other bugs. 😄

**Comment by saschanaz** [comment]
Pinging @Swapnilr1, are you still working on this? I found this would be helpful for my other branch.

**Comment by Swapnilr1** [comment]
@saschanaz Yeah I am working. Sorry didn't realise this was urgent, if I am not able to send in a PR tomorrow, you can do it if it's blocking something you are working on.

**Comment by saschanaz** [comment]
It’s not strictly blocking so no need to be sorry! Just wanted to be sure this is in progress 😁

________________________________

**Comment by Swapnilr1** [comment]
@saschanaz I have not been able to resolve issues with tests. So I need guidance on that and this might take some time to get completed. I hope it is OK.

**Comment by saschanaz** [comment]
Try open a draft PR so that others can see what the problem would be. Maybe @sidvishnoi can help?

________________________________

**Comment by Swapnilr1** [comment]
I have opened #2228. Thanks for the suggestion, I will ping sidvishnoi
