### ISSUE TITLE
Copy button showing up in print view

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2144]
## Important info

* URL to affected spec:
* ReSpec version: Click the ReSpec pill (e.g., 20.0.1).
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 
When printing from a spec: 

<img width="524" alt="screenshot 2019-03-07 13 24 46" src="https://user-images.githubusercontent.com/870154/53927946-8cc1ba80-40dc-11e9-907f-a2519f33ceea.png">

But what I was expecting?:
The button not to be there.

Optional, steps to reproduce:
 1. File -> print as PDF...

**Comment by marcoscaceres** [comment]
Should also check what is going on with the fonts.... those serifs in heading 🤢

**Comment by pradeepgangwar** [comment]
Let me try this one.

**Comment by ThobyV** [comment]
@marcoscaceres it seems to be an issue with the absence of print media queries for the button. I've made a fix in my branch but @pradeepgangwar can send a p.r let me know if you might need any help @pradeepgangwar

**Comment by pradeepgangwar** [comment]
@ThobyV what are steps to reproduce it on a spec. I didn't get that button when running examples from examples folder.

**Comment by ThobyV** [comment]
Try using the `basic.html` sample spec from the examples folder (https://github.com/w3c/respec/blob/develop/examples/basic.html#L1-L114).  as It contains a `<pre>` class usage example (i think it used for code snippets in spec). Then try to print the generated spec page as a pdf or so from browser.

**Comment by ThobyV** [comment]
I think you should be able to see the code snippet copy/paste button in an unusual position in the pdf file preview unlike where it is on a spec webpage. I don't think chrome has the issue but it seems to be reproduceable on Firefox.

**Comment by pradeepgangwar** [comment]
@marcoscaceres @ThobyV I am not able to reproduce this bug. I tried using examples in examples folder but they seem to work fine. All the copy buttons there have `removeOnSave` class which has already been set to hide on printing here. https://github.com/w3c/respec/blob/3149bac1783f6c80e81d710287bb77f57782b177/assets/respec2.css#L236

It would be great if you can help me finding the exact spec and version where this issue was seen.

**Comment by ThobyV** [comment]
@pradeepgangwar you  are right, I think the bug is only reproduced if you do not already have a cached version of the css loaded from w3c hosted css if I am right.

Try to refresh the spec page more than once checking the print preview each time using `ctrl+shift+r` on your browser  (force page refresh). 

I think a solution to the bug would be to add `display: none !important` instead of `display: none` to the `removeOnSave` print query. (this worked here). Perharps there is a conflict in css from host vs css compiled in build. I Check this with the stylesheet editor.

Currently, I have the latest version of respec (24.4.4) in master branch, it appears bug is still there.

Also are you using chrome browser? Bug was reproduced on firefox 65.x (also recent update).

**Comment by ThobyV** [comment]
I am using `basic.html` spec to reproduce the bug since. It has (code snippets and the copy button will show). 

Also, another solution might be to write print media query specific for the `.respec-button-copy-paste` class in `assets/webidl.css`. (as an alternative to not using !important for `.removeOnSave` class instead). 

@marcoscaceres what do you think about this? Is it right way to approach the issue?

**Comment by marcoscaceres** [comment]
Putting and explicit rule for  `.respec-button-copy-paste` into the print media rules seems like the best solution. Not a huge fan of `!important`.

**Comment by marcoscaceres** [comment]
Button is still showing up in Firefox even after #2150, unfortunately. @ThobyV, you want to give it a shot and see if you can figure out a fix?

**Comment by ThobyV** [comment]
Sure @marcoscaseres I'll take it up. I had Journeyed to school so I just settled yesterday.

**Comment by marcoscaceres** [comment]
closed via #2156
