### ISSUE TITLE
Regression: normative biblio things end up in informative section

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2180]
## Important info

* URL to affected spec: https://w3c.github.io/payment-request/#references
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: 
Duplicate bibliographical entries:
https://w3c.github.io/payment-request/#references

DOM and dom, weidl and WEBIDL

But what I was expecting?:

For there to be no duplicates. 

Optional, steps to reproduce:
 1. See https://w3c.github.io/payment-request/#references

**Comment by Swapnilr1** [comment]
@marcoscaceres Changing https://github.com/w3c/respec/blob/f7177978f10ec844b95a5066234df9b01f374744/src/core/xref.js#L245 to 
`closestInform && !normative && ` fixed the issue when I tested this. This is just a quick hack I did by poking around - I am not sure if this is a valid fix, since I don't exactly know what the module is doing. So I have not made a PR for now.

**Comment by marcoscaceres** [comment]
@Swapnilr1 thanks for investigating. I'll have a look, but what you describe above like might be a reasonable fix.
