### ISSUE TITLE
Tests needed for core/contrib

### ISSUE THREAD

**Issue by devanshbatra04** [w3c/respec#2182]
There are a few things wrong with ```core/contrib```.
https://github.com/w3c/respec/blob/develop/src/core/contrib.js#L44 does not allow for token-only Authentication, which is incorporated in ```core/github```
https://github.com/w3c/respec/blob/develop/src/core/contrib.js#L29 too fails as it requires another asynchronous resolution of the response to get a JSON.
I have solved both of these in #2181 
However, I think we should write tests for this module once that gets merged.

**Comment by marcoscaceres** [comment]
A few more tests would be really great.

**Comment by markasoftware** [comment]
Should these tests make a real call to the GitHub API or would it make more sense to mock out core/github?

**Comment by marcoscaceres** [comment]
These would be mocked out, similarly to what we did with GitHub issues:
https://github.com/w3c/respec/tree/develop/tests/data/issues

**Comment by algobot76** [comment]
@marcoscaceres Can I work on this issue?

**Comment by markasoftware** [comment]
I am fixing several issues with core/contrib.js while working on this -- would it be appropriate to output each contributor/commenter as a link to that person's profile instead of just their username? What about an attribute on the `gh-commenters` or `gh-contributors` element that controls whether it's a link?

**Comment by devanshbatra04** [comment]
@markasoftware I really don't understand why would you need the full URL or conflict with the ReSpec file path.
You probably already figured this out but ReSpec hosts a local server with your ReSpec directory which you can trigger using npm start, typically on port 5000. This makes the location of ReSpec directory on your system irrelevant. 
This means that if you visit [http://localhost:5000/examples/basic.html](http://localhost:5000/examples/basic.html) it will always open up the ```basic.html``` template, regardless of where the repo was cloned.

This means that http://localhost:5000/tests/data/issues/1540 returns the JSON at [this file](https://github.com/w3c/respec/blob/develop/tests/data/issues/1540) which is a mock for an issue returned by the github API from a URL endpoint like https://api.github.com/repos/:owner/:repo/issues/1540. Full documentation [here](https://developer.github.com/v3/issues/#list-issues-for-a-repository).
We have set up the config and tests in such a way that ```api.github.com/repos/:owner/:repo``` always maps to ```localhost:5000/tests/data```. 

I see the problem is that the GitHub API for fetching users is ```api.github.com/users```, which is different from ```api.github.com/repos/:owner/:repo```. The correct way to handle this would be editing ```core/github``` to set conf.github-api as ```api.github.com``` instead of the repos endpoint, and refactoring quite a bit. 

You can then create a mock repository on GitHub with a couple of issues and comments, collaborators, contributors, see what all requests the module makes from the browser and set up the corresponding endpoints. I did try this out and there were about 7-8 requests being made for a small repository. So that would require just as many files in appropriate directory. (You would also need to add the remaining requests header to the server configuration file).

I am not sure if it's worth all the effort though.

**Comment by markasoftware** [comment]
Thanks for the writeup @devanshbatra04 

Wow, I must have completely spaced out to forget that there was a server running there. But, if I understand right, port 5000 is only used with `npm start`/the development server. When running tests with Karma, a different port is used. While I see now that you could hardcode that port (9876, I think) into the mock data, it would become very fragile -- providing the `--port` option to Karma would break the tests. 

> I see the problem is that the GitHub API for fetching users is api.github.com/users, which is different from api.github.com/repos/:owner/:repo. The correct way to handle this would be editing core/github to set conf.github-api as api.github.com instead of the repos endpoint, and refactoring quite a bit.

I can't follow your logic here; Why is that a problem? The request to `/users` doesn't involve `githubAPI` anymore, because the fully qualified URL is returned from `${githubAPI}/issues`.

Currently, I am modifying core/github to add a `githubAPIBase` property to `conf` with a value like `https://api.github.com`. core/contrib won't do `new URL(stuff_returned_from_github)` anymore, but rather `new URL(stuff_returned_from_github, githubAPIBase)`. In production this will have no effect (because stuff_returned_from_github has protocol and origin in it), but during tests githubAPIBase will be set to `window.location.origin` and we get the flexibility we need.

**Comment by devanshbatra04** [comment]
Karma creates a separate server for running the tests. 
The tests do run the development server as well without you explicitly running npm start for serving all the dependencies, build files and the mocks. These are two different servers for different usages. You don't need to worry about the Karma's test runner server (the 9876 one) at all.

Look at it this way. As of now, ```githubAPI = api.github.com/repos/:owner/:repo``` but during testing, ```githubAPI = ${window.location.origin}/tests/data```. Which I think is what you want to do. Look at [issues-notes-spec](https://github.com/w3c/respec/blob/d72aeb6fd5f2afbf152c421b3153e9c4d172df7c/tests/spec/core/issues-notes-spec.js) which is what should be copied here.
We probably only want the final API endpoints in the config. So you will need to handle the githubAPIBase logic inside ```core/github```.

**Comment by markasoftware** [comment]
> Karma creates a separate server for running the tests.
The tests do run the development server as well without you explicitly running npm start for serving all the dependencies, build files and the mocks. These are two different servers for different usages. You don't need to worry about the Karma's test runner server (the 9876 one) at all.

I don't believe this is correct. `npm run test:karma` on my machine doesn't do anything on port 5000. All test data and mocks appear to be served out of `127.0.0.1:9876`. I can do `curl 127.0.0.1:9876/tests/data/issues/1540`, for example.

issues-notes doesn't involve endpoints which link to other endpoints, which is the root of the problem here.

**Comment by devanshbatra04** [comment]
My bad, you are right here. That's why we use window.location.origin in specs like these at [issues-notes-spec](https://github.com/w3c/respec/blob/d72aeb6fd5f2afbf152c421b3153e9c4d172df7c/tests/spec/core/issues-notes-spec.js#L135) 
I also see your point now, the mock json will have a hardcoded URL.
