### ISSUE TITLE
self-link doesn't link to correct id

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec#2283]
## Important info

* URL to affected spec: https://w3c.github.io/payment-request/
* ReSpec version: 24.16.1
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

Clicked "Changes since last publication" heading under SOTD, which linked to `#sotd` instead of `#changes-since-last-publication`

**Comment by marcoscaceres** [comment]
Yeah, no idea what happened there. I spotted that too :(

**Comment by yuanchuan** [comment]
Somehow the `id` has not been generated.

According to the source code, the section with the class name `.introductory` will be skipped to be traversed along with all its child sections: 

https://github.com/w3c/respec/blob/a624099f4a32e87f8cbdf359bb801d513018df7f/src/core/structure.js#L108

While the `sotd` section always contains a `.introductory` class name:

https://github.com/w3c/respec/blob/a624099f4a32e87f8cbdf359bb801d513018df7f/src/w3c/headers.js#L506

So the `changes since last publication` section which is inside the `sotd` section will be untouched. 

I don't know if this by design. By adding an `id` in the markup manually should be a quick fix until the issue has been resolved. 

```html
<section id="changes-since-last-publication">
  <h3>
    Changes since last publication
  </h3>
</section>
```

**Comment by marcoscaceres** [comment]
@yuanchuan, thanks for investigating... what it is doing partially correct, but an id should be assigned irrespective of it being in an `.introductory` section.
