### ISSUE TITLE
[Feature request]: output contributors as list items

### ISSUE THREAD

**Issue by scottaohara** [w3c/respec#2446]
Regarding inclusion of GitHub contributors and commenters in [this HTML AAM PR](https://github.com/w3c/html-aam/pull/228#issuecomment-514471005), just discussed with @marcoscaceres the idea of allowing the `gh-commenters` and `gh-contributors` to output as list items if the IDs were found to be on `ul` elements.

**Comment by sidvishnoi** [comment]
GitHub v3 APIs for reference: 
- Contributors to a repo: [documentation](https://developer.github.com/v3/repos/#list-contributors ), [example](https://api.github.com/repos/w3c/html-aam/contributors)
- Issue commenters: [documentation](https://developer.github.com/v3/issues/comments/#list-comments-in-a-repository), [example](https://api.github.com/repos/w3c/html-aam/issues/comments)

Both APIs get us `user.login`, so we would need a mapping of `user.login` to `user.name` if we want to display names instead of just GitHub usernames. The `/users/:user` endpoint ([example](https://api.github.com/users/jasonkiss)) can get us the names, but we are very likely to go beyond the rate limit. But we can cache this mapping at respec.org.

Looked into GraphQL v4, but it doesn't support listing contributors yet.

A mix of GraphQL (v4) and REST (v3) APIs at https://respec.org seems like a good idea to me. 
WDYT? @marcoscaceres @saschanaz

**Comment by scottaohara** [comment]
Just checking in for any further movement on this?  

If not, no worries.

**Comment by sidvishnoi** [comment]
Hi Scott,
Had a discussion on this with Marcos earlier and we do have some work under progress.

Regarding `gh-contributors`:  Do we want to display only GitHub login names of contributors or full names of contributors (with link to GitHub profile maybe?)?

Regarding `gh-commentors`: We're not sure of supporting this feature. Listing all issue commentors requires traversing a really long history of issues (even when we're trying to find unique authors only). I tried it once on html-aam, and it took nearly 7 minutes, which is totally unacceptable. Even with extensive caching, the queries are not fast enough. Also, IMO, listing all commentors in a repository doesn't make sense, as there maybe spam or +1 comments, which shouldn't be listed as _meaningful contributors_ for a spec. What do you think?

**Comment by scottaohara** [comment]
i'm more concerned with contributors tbh. while some people may primarily contribute through comments, which are appreciated, i'd submit that'd be on the maintainers of a repository to determine a way of giving attribution to them.  e.g. i wouldn't expect to be listed as a contributor to respec per just my comments here! :)

regarding info for contributors... seems all 3 bits of info would be good?  for instance, i'd prefer to use people's full names, but if that's not available then their github user name.  In either situation, i think links would be nice (but could also live without links if need be, and could even just construct them myself with the github user name if it were provided)

**Comment by sidvishnoi** [comment]
Okay. For now, we'll work on listing contributors only.
