### ISSUE TITLE
TOC layout error when served by GitHub pages

### ISSUE THREAD

**Issue by wetneb** [w3c/respec#2524]
## Important info

* URL to affected spec: https://reconciliation-api.github.io/specs/
* ReSpec version: 24.33.1
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

What happened (e.g., it crashed)?: The spec renders fine locally or over HTTP but when served on GitHub pages, the Table of Contents is laid out incorrectly (as a horizontal rather than vertical list) and other elements are not correctly rendered.

But what I was expecting?: A consistent rendering behavior locally (with `python -m SimpleHTTPServer`) and remotely (with GitHub pages)

Optional, steps to reproduce:
 1. git clone https://github.com/reconciliation-api/specs
 2. cd specs
 3. open index.html
 4. Compare to the live version: https://reconciliation-api.github.io/specs/
 5. Check that both HTML files are equal (wget https://reconciliation-api.github.io/specs/index.html -O live.html ; diff live.html index.html)

**Comment by sidvishnoi** [comment]
Seems like a GitHub pages issue. Serving via [githack](https://raw.githack.com/reconciliation-api/specs/master/index.html) also works fine.
I see a CSP error with GitHub pages, which I think is due to missing `schemas/reconciliation-query.json`. gh-pages renders a 404 HTML page, which has a CSP that is violated on `data-include`. Blocking the request to `schemas/reconciliation-query.json` makes it work fine. 

I would suggest adding a `schemas/reconciliation-query.json` or not doing `data-include` for that until you can add it.
Please reopen this if you believe it's a ReSpec bug.

**Comment by sidvishnoi** [comment]
So the gh-pages' 404 page have some CSS that conflicts with ReSpec's :rofl: 
![image](https://user-images.githubusercontent.com/8426945/65773229-8159dd80-e159-11e9-8fb6-d69f2ca02bff.png)
