### ISSUE TITLE
Teach release script about "enhancement"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2618]
The release script doesn't know how to treat commits prefixed with "enhancement"... they should be treated the same as "feat". The kids are also using "enh()" as a shorthand, I hear. We might want to support that too because "enhancement" eats like half a commit message.

**Comment by marcoscaceres** [comment]
Relevant bits to change:
https://github.com/w3c/respec/blob/67edc4971ece9c91acccc7b03bc15a47cb136363/tools/release.js#L134

And, in particular:
https://github.com/w3c/respec/blob/67edc4971ece9c91acccc7b03bc15a47cb136363/tools/release.js#L196

**Comment by marcoscaceres** [comment]
@janiceshiu would you be ok to take this one? Should be a quick one. We can probably just use the same emoji that we use for "feat".

**Comment by marcoscaceres** [comment]
(the release script has no tests ... because that's how we roll 🔥🦹‍♀️🔥 )

**Comment by sidvishnoi** [comment]
> The kids are also using "enh()" as a shorthand, I hear. 

:rofl: 

> We might want to support that too because "enhancement" eats like half a commit message.

:+1:

**Comment by saschanaz** [comment]
Or just `enh`, because we don't support longhands e.g. `accessibility`, `documentations`, and `feature` 😁

**Comment by marcoscaceres** [comment]
Whatever is most natural. So long as we all agree on what to use and we are not overly restrictive.

**Comment by saschanaz** [comment]
BTW, what kind of enhancement are we talking about? Can't we use `feat`, `fix` and `refactor` there?

**Comment by marcoscaceres** [comment]
That's a great question... because it makes me think we are solving the wrong problem. Maybe what we actually want is a GitHub action that checks that every pull request starts with feat, fix, refactor, or one of our known types.

**Comment by janiceshiu** [comment]
Since we're discussing naming... is there a guide somewhere that contributors - especially new ones - can refer to when naming their PRs and commits?

back when i [first contributed to respec](https://github.com/w3c/respec/pull/2544), i read the [developer's guide](https://github.com/w3c/respec/wiki/Developers-Guide) and didn't see anything about the format. I ended up guessing that the pattern is something along the lines of `$TYPE(path/to/changed/file): $SUMMARY_OF_PR` by looking at [recent commits to master](https://github.com/w3c/respec/commits/develop). I named my [recent PR](https://github.com/w3c/respec/commit/6cc536b3a0ad490693db593e218427d7519d9790) by guessing and imitating the same pattern.

Also - now that I look at recent commits again - some commits with the filename have the filename's extension, and others don't. If this is important, perhaps we could standardise it and make it clear.

**Comment by saschanaz** [comment]
We are generally following [AngularJS conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153#format-of-the-commit-message). This should be added to the guide too 👀

**Comment by saschanaz** [comment]
The developer's guide doesn't really seem to be a contribution guide. Should we also add a GitHub pull request template too?

**Comment by janiceshiu** [comment]
> We are generally following [AngularJS conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153#format-of-the-commit-message). This should be added to the guide too 👀

I did not realise this. Yes - a guide would be good. We do allow more types than the linked doc though. For example, we have `l10n` and `breaking change`. Thus, perhaps we should write a respec-specific guide? We could always link to the original inspiration.

---

> The developer's guide doesn't really seem to be a contribution guide. Should we also add a GitHub pull request template too?

This would be good, yes. To start, we could include something like 

```
Fixes #issue_number 

[] All tests pass
```

Regarding the contribution guide - things such as a reminder to run `prettier` on one's code would also help.

^ the suggestions above are based off my experience as a new contributor to respec - these are things I didn't know and figured out by trial and error or by someone letting me know.

**Comment by marcoscaceres** [comment]
Ok, let’s start with adding the labels to the docs and saying we roughly follow Angular. We should add a CONTRIBUTING.md file too, with the labels and a link to the developer guide.

**Comment by sidvishnoi** [comment]
Closing based on https://github.com/w3c/respec/issues/2618#issuecomment-564496630
