### ISSUE TITLE
Dark mode in respec

### ISSUE THREAD

**Issue by jakubklimek** [w3c/respec#2651]
Respec is currently missing support for dark mode, e.g. using the `@media (prefers-color-scheme: dark)` CSS media query.

Is there an interest in implementing such a feature?

I gave it a try in our [respec fork](https://github.com/opendata-mvcr/respec) that we use for data standards in Czechia, you can see the result (with dark mode enabled) e.g. here: https://ofn.gov.cz/rozhraní-katalogů-otevřených-dat/2019-04-04/

I know it is far from ideal and also incomplete (only CSS of features that we use were modified). I basically extracted all CSS color definitions into CSS variables and added a dark color pallette in [base.css](https://ofn.gov.cz/static/css/base.css) and the [CSS assets](https://github.com/opendata-mvcr/respec/tree/develop/assets).

**Comment by marcoscaceres** [comment]
Very nice 👍 the base.css changes would need to go through the w3c (tr-design project repo) - but if they accept it, I think this would be a great addition!

**Comment by KarimCypher** [comment]
Hey, @marcoscaceres I would like to work with this issue if no is working on this issue. This is my first contribution so it would be helpful if you could help me out a bit working on this issue.

**Comment by marcoscaceres** [comment]
@Fahad999, this is probably not a good issue to to work on, as @jakubklimek has already done all the work :) If something else comes up that's easy to fix, I'll let you know.

**Comment by saschanaz** [comment]
https://github.com/w3c/tr-design/pull/202 is merged. What work items are left here?

**Comment by sidvishnoi** [comment]
We need to match with the dark theme when tr-design releases new base.css (we should have our patches ready before that though). I collected a few action items (mostly use css variables):

- .warning, .example (use base.css styles instead our own)
- ReSpec UI
- TOC markers color
- dfn panel, mdn panel
- lighten down caniuse colors (they look too bright in dark mode, maybe we can use ones from new caniuse website)
- syntax highlight colors
- webidl header

**Comment by dontcallmedom** [comment]
a recent change in htmldiff makes getting this fixed more time sensitive https://github.com/w3c/htmldiff-ui/issues/12#issuecomment-1938308352

**Comment by daniel-montalvo** [comment]
Just cross-referencing an issue that got opened in ARIA because of this problem
https://github.com/w3c/aria/issues/2133

**Comment by cookiecrook** [comment]
Also please verify the dark/light variants work in the matrix with standard/increased contrast `@media (prefers-contrast: more)`

|                       | Default Contrast | Increase Contrast |
| ------------- | ------------- | ------------- |
| Dark Mode | `@media (prefers-color-scheme: dark)` | `@media (prefers-color-scheme: dark)` <br> `     and (prefers-contrast: more)` |
| Light Mode | `@media (prefers-color-scheme: light)` | `@media (prefers-color-scheme: light)` <br> `     and (prefers-contrast: more)` |


Ideally tested with "increase contrast" setting on Mac/iOS, and "high contrast mode" on Windows.

**Comment by sidvishnoi** [comment]
I'll be having some time next week, so will likely be working on this 🤞
This issue is highest priority for me to finish.

**Comment by nigelmegitt** [comment]
This could have a significant impact on specs that specify some aspects of styling themselves, which have not so far had to deal with dark mode. Those could be custom CSS or diagrams with transparent backgrounds for example.

Would it be possible to put support for dark mode behind an options setting or similar so that it can be permitted per document and so that the current behaviour doesn't change underneath other documents? I'm worried about documents that end up being only partially adapted to dark mode and therefore actually unusable.

For a concrete example, some of the entries in the table at https://www.w3.org/TR/dapt/#disposition-of-features-and-extensions are marked as "required" in white text in a black background block. In dark mode those colours should be reversed; since the styling is defined locally it would need editorial work to fix it up for dark mode, as well as further accessibility testing.

**Comment by sidvishnoi** [comment]
I think I'll add option to opt-out, but it'll be enabled by default as most specs (and referenced issues) likely want to make use of it.

If someone wants to update specs before this gets shipped, set `respecConfig.darkMode = false`.
