### ISSUE TITLE
No GSoC in 2020 - Please read! 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2680]
**ReSpec is NOT part of GSoC 2020.**  

If you'd like to see Mozilla's GSoC proposals: 
http://github.com/mozilla/GSOC2020/tree/master/proposals

Any questions, please file a bug:
http://github.com/mozilla/GSOC2020/issues

**Comment by Ayush23Dash** [comment]
Hi,can you please help me with what kind of coding skills are requires. I have learnt how to use npm packages to deal with the extremities of a webapp and want to contribute to open source via gsoc.
Looking forward for your reply

**Comment by sidvishnoi** [comment]
Please have a look at previous years' GSoC for more information at https://github.com/w3c/respec/issues/1502 and https://github.com/w3c/respec/issues/2124

**Comment by AnkitaPriya042** [comment]
Any updates on GSOC2020 @marcoscaceres  @sidvishnoi

**Comment by marcoscaceres** [comment]
Not yet. Hopefully by tge end of the week.

**Comment by AnkitaPriya042** [comment]
What are the updates @marcoscaceres . Its the end of the week

**Comment by marcoscaceres** [comment]
We’ve decided not to take part this year.

**Comment by gittysachin** [comment]
Hi @marcoscaceres @sidvishnoi, can you please tell me what are the repositories of Mozilla that are going to be selected for GSOC'20. So that I would be able to contribute to those repositories. I'm skilled in C++, Git, JavaScript, HTML, CSS, React, Redux, NodeJS and other frameworks of JavaScript. 

I saw that GSOC 2020 proposals list in the above-given link. But the actual repositories of those projects are not clear to me. Talking about the devtools, there are many repos for devtools in firefox-devtools. I tried to contribute to one of them named profiler. But it would be so helpful for me if you could tell me actual names. Thanks.

**Comment by marcoscaceres** [comment]
Hi @gittysachin, please ask here instead: http://github.com/mozilla/GSOC2020

**Comment by sidvishnoi** [comment]
Closing as proposal period is over.
