### ISSUE TITLE
Add support for "group(s)"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2745]
It would be nice if ReSpec supported just having a "group" configuration option, that would pull all the relevant information about a working group from somewhere. 

Group should be a string, like "WebApps". That would map to a W3C Group ID, and we could then pull the group information from the W3C API. 

And example of this is done here:
https://w3c.github.io/webappswg/

We might also need to deal with join group specs... but having single group support would be great.

**Comment by sidvishnoi** [comment]
How do we plan to use the group information from the API? The only group related info I found is presently being used in SOTD (_"This document was published by the Web Applications Working Group as a Living Document."_)

**Comment by marcoscaceres** [comment]
Oh, the IPR link, the mailing list, the group’s actual full name, etc. All sorts of goodies.

**Comment by sidvishnoi** [comment]
I see. `wg`, `wgURI`, `wgPatentURI`, `wgPublicList` configuration options to be precise.

Problems to be solved:
- Finding group id from a group short name. W3C API doesn't provide any such information.
- We need to use a common API key (otherwise ask spec authors, which is uncool), so API limits will be an issue.
- W3C API is a proper rest API, which means, we've to traverse a request tree to find relevant information, which will be slow:
```
group => groupID
https://api.w3.org/groups/{groupID}/
  (gives us `wg` as `name`)
  (gives us `wgPatentURI` as `_links.pp-status.href`)
  (gives us `wgURI` as `_links.homepage.href`)
If we want `wgPublicList`, go to https://api.w3.org/groups/{groupID}/services
  for each serviceID in _links.services[title="Mailing Lists"]:
    Visit https://api.w3.org/services/{serviceID}
    (gives us `wgPublicList` as `shortdesc`)
```

This API should've been a GraphQL API. Looks like we might have to do it on respec.org (which is more work!). We'll get benefit of having a single request with only required fields and caching to stay within API rate limits (and not asking editors to add an API key).

**Comment by saschanaz** [comment]
Maybe we can skip the public list, as everyone uses GitHub now.

**Comment by marcoscaceres** [comment]
Some groups still like their mailing lists, but I agree it should be opt-in somehow.

**Comment by marcoscaceres** [comment]
We can pull data from this new datasource: https://www.w3.org/PM/Groups/chairboard.html?gid=114929

**Comment by sidvishnoi** [comment]
It's pulling data from W3C API itself...
