### ISSUE TITLE
generate ECHIDNA manifests

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#2970]
Be nice if respec2html could generate ECHIDNA manifests as a command line option. It could pull all the local images from a document, and list them in the ECHIDNA manifest. It would also need to handle the status.. but that could be provided as an argument.

**Comment by xfq** [comment]
This is indeed a useful feature. From my experience, respec2html needs to look at these places:

* `<link href="...">` (mostly for spec-specific stylesheets, but also for favicons because some specs use their own logo for favicons)
* `src` in `img`/`script`
* `@font-face` (some specs use web fonts, such as [charmod-norm](https://github.com/w3c/charmod-norm/blob/gh-pages/local.css))
* Other possibilities: Worker? `src` in `video`/`track` elements? (I'm not aware of any spec uses these though...)

**Comment by marcoscaceres** [comment]
Good suggestions @xfq! thanks!

**Comment by sidvishnoi** [comment]
I've been experimenting with this at https://github.com/sidvishnoi/subresources 
It'll be useful in https://github.com/W3C/spec-prod also.

**Comment by sidvishnoi** [comment]
This might no longer be needed if we go with spec-prod route, which already deploys minimal set of dependencies using https://github.com/sidvishnoi/local-assets/.

**Comment by marcoscaceres** [comment]
Agree. Let's not do this here.
