### ISSUE TITLE
Provide template/theme for OASIS

### ISSUE THREAD

**Issue by sspeiche** [w3c/respec#300]
I have started the work in my fork, at https://github.com/sspeiche/respec and sample at http://sspeiche.github.io/respec/examples/basic-oasis.html.  Looking for guidance on how to properly weave it in or place on its own branch.  I can squash the commits together but right now it is sort of neatly inserted next to the w3c stuff.

**Comment by sspeiche** [comment]
@darobin I'm not sure how best to proceed with this.  I'm in a fairly good place with it, just need to sync it up.  OASIS staff is on board with using it.  Just submit pull request and it gets included here?

https://github.com/sspeiche/respec/tree/feature/oasis-style

**Comment by akuckartz** [comment]
+1 for this collaboration between OASIS and W3C

**Comment by darobin** [comment]
Hi @sspeiche, there are two basic approaches we can take.

The first is to fold this into ReSpec. It's not a problem in itself, but my area of concern is code size. Everything we add that only a subset of people use hurts people. If it's just a template, it's probably not a big deal but you get the idea. In this case, I think that's not the best option. (Though I'm all for collaboration!) This isn't just for download but also for development complexity (testing surface and turnaround, etc.)

The second alternative is to build a separate profile. The great thing is that you've already done a lot of that! The problem is that I think you did it in a way that makes life harder for you — but that's solvable!

Basically, instead of creating your own profile in a branch of a fork, you can have a profile that brings in ReSpec *as an external dependency*. Setting up the build is a little convoluted, but it's not the end of the world. The respec-docs repository has taken this approach. Basically you:

1. Include ReSpec as a dependency in your `package.json`, and npm install it. https://github.com/w3c/respec-docs/blob/gh-pages/package.json#L7 (but use a more recent version)
2. Tweak your profile script a little bit so that it knows how to load the dependencies from the right directory. https://github.com/w3c/respec-docs/blob/gh-pages/beryl/beryl.js
3. Have a build tool that matches that setup. https://github.com/w3c/respec-docs/blob/gh-pages/tools/build.js. Note that it doesn't have to be this complicated, this one builds up a styling system as well for instance.


3.

**Comment by lonniev** [comment]
@sspeiche I agree with @darobin on the recommendation for how to include rather than evolve ReSpec.

(If there is some cloudy IDE for doing this javascript coding, I am willing to attempt the 3 step recipe above. I'm still primarily a server-side programmer and have a Mac/Eclipse environment for that coding. If I have to set up some nifty new JS environment, it may take more time to get all the pieces and not snafu my existing dev world. What are you using? I think I still have a Cloud9 https://c9.io/ account floating around somewhere.)

**Comment by lonniev** [comment]
I reanimated my Cloud9 account, reconnecting it to GitHub. Therefore, decide what you want to do and advise me when you are done. Thanks.

**Comment by marcoscaceres** [comment]
Unfortunately, we don't have the resources to do this :(
