### ISSUE TITLE
Respec should allow the inclusion of a canonical URL

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#317]
Basically, something like:

```
<link rel="canonical" href="http://picture.responsiveimages.org">
```

Use case: to tell Google not to treat WDs on TR as canonical and instead see the Editor's drafts as canonical.

**Comment by darobin** [comment]
Yeah, markup is easier to handle than configuration since it works the same everywhere and you're likely to know how to do it even if you only heard about ReSpec five minutes ago. The configuration language is slowly turning into Sendmail, it could use a hand.

There are cases in which configuration is better than markup, but the markup has to be pretty complicated.
