### ISSUE TITLE
Add support for partial interface references

### ISSUE THREAD

**Issue by plinss** [w3c/respec#3264]
**Is your feature request related to a problem? Please describe.**

Partial interface definitions make it hard to see the full interface. Avoiding the use of partials can be a spec maintenance nightmare.

**Describe the solution you'd like**

It would improve matters if ReSpec used the Shepherd data to locate the base interface definition and all the partials referring to it and added links between them.

**Describe alternatives you've considered**

See https://github.com/w3ctag/design-principles/issues/99#issuecomment-654518930

**Can you or your organization fund the work or help with development?**

Consider me on standby to add any needed support to the Shepherd data.

**Additional context**

Corresponding Bikeshed issue: https://github.com/tabatkins/bikeshed/issues/1843

**Comment by sidvishnoi** [comment]
Hi Peter!
I'm generally supportive of this idea. @saschanaz might have more to say. 

Though, we've [recently](https://lists.w3.org/Archives/Public/spec-prod/2020OctDec/0015.html) moved from Shepherd to w3c/webref. I think we should coordinate with folks at webref about adding data support for this if we move ahead.

**Comment by saschanaz** [comment]
Isn't this already the case? I see [Pointer Lock](https://w3c.github.io/pointerlock/#extensions-to-the-element-interface) links to the original interface properly, although many specs still define their own definitions that link to external specs.

**Comment by tidoust** [comment]
In Webref, information about partial interfaces defined in a given spec is available in `idlparsed` extracts under the `idlExtendedNames` property, e.g. in [idlparsed/pointerlock-2.json](https://github.com/w3c/webref/blob/master/ed/idlparsed/pointerlock-2.json#L12) for Pointer Lock. It should be relatively easy to create views per IDL interface using that info.

In the same vein (but partial interfaces still need to be handled separately because they extend the base definition), the info about which specs link back to a specific term is available in `links` extracts in Webref, e.g. in [links/pointerlock-2.json](https://github.com/w3c/webref/blob/master/ed/links/pointerlock-2.json#L32) for Pointer Lock.

**Comment by saschanaz** [comment]
>although many specs still define their own definitions that link to external specs.

BTW, should we warn this as an antipattern?

**Comment by tidoust** [comment]
A couple of notes following discussion with @dontcallmedom:
1. My understanding from the TAG's discussion is that this is more specifically about surfacing the information in the specs themselves. If the purpose is rather simply to find all specs that extend an interface, [WebIDLPedia](https://dontcallmedom.github.io/webidlpedia/) (is ugly but) has that info, e.g. for [`Element`](https://dontcallmedom.github.io/webidlpedia/?idlname=Element). The tool is based on Webref.
2. We'd be happy to surface the information in a more directly useful way in Reffy/Webref, see https://github.com/w3c/reffy/issues/472. Feel free to chime in if you have specific needs there.

**Comment by plinss** [comment]
@tidoust, you are correct, while having external tools to reconstruct interfaces is useful, the original concept here is to have the information available directly in the specs, just auto-generated.

Let me give a concrete example, there's a spec A, that defines interface `Base`, specs B and C define partial interfaces of `Base`.

Of course both specs B and C should have links to the definition of `Base` in spec A. But *also*, the next time spec A is run thorough a generator, it should gain links to the partial definitions of `Base` in specs B and C. Something like some text immediately after the definition of `Base` to the effect of "this interface is extended &lt;a href="specB#base"&gt;here&lt;/a&gt; and &lt;a href="specC#base"&gt;here&lt;/a&gt;." 

Ideally, somewhere in spec A (likely an appendix) there should also be a complete definition of `Base` that includes the partial portions from specs B and C (with appropriate links to B and C as needed). This last bit requires some additional information about where in the definition of `Base` the partial portions should live (the ordering problem mentioned in the TAG issue), this should probably be specified as metadata in the partials.

**Comment by dontcallmedom** [comment]
(for reference, I have added supported for aggregating fragments across partial interfaces/dictionaries/namespaces to WebIDLpedia, see e.g. https://dontcallmedom.github.io/webidlpedia/?idlname=HTMLMediaElement)

**Comment by sidvishnoi** [comment]
> Ideally, somewhere in spec A (likely an appendix) there should also be a complete definition of Base that includes the partial portions from specs B and C (with appropriate links to B and C as needed). 

Maybe instead of each base spec, we can have a central location like Dominique's WebIDLPedia and link to it from ReSpec/Bikeshed?

**Comment by plinss** [comment]
Linking to an external site that has the combined interfaces would be an improvement over the status-quo, and I'd personally consider that an MVP. I would like to see them inline in the specs tho (useful when reading a spec offline).

**Comment by marcoscaceres** [comment]
> Ideally, somewhere in spec A (likely an appendix) there should also be a complete definition of Base that includes the partial portions from specs B and C (with appropriate links to B and C as needed). This last bit requires some additional information about where in the definition of Base the partial portions should live (the ordering problem mentioned in the TAG issue), this should probably be specified as metadata in the partials.

I don't think this is a good idea, tbh. This duplication risks getting out of sync and being confusing. 

Few things... Engines already handle `partial` without any issues, so the maintenance cost is pretty small (I've implemented a ton of these in Gecko, so that's at least my personal experience). The only burden was having to add the URL from where the interface came from. For example, Web Share: 

https://github.com/mozilla/gecko-dev/blob/9f76a47f4aa935b49754c5608a1c8e72ee358c46/dom/webidl/Navigator.webidl#L323-L333

(you can see the rest of the partials for `Navigator` there... it's not amazing, but it's not that bad either)

However, I'd agree that pushing partials back into base interfaces is a worthy goal - because it would add some [procedural safeguards](https://whatwg.org/working-mode). However, one would still need a back/forwards reference in each spec to hook things up properly.

Tooling could help here, but so we would need to change the Process or the culture around `partials`... like, ReSpec could disallow partials on REC documents, forcing spec authors to push their partials to the Base specs.

**Comment by marcoscaceres** [comment]
Going back to the TAG's issue, I see @dbaron wrote:

> Discussed in the TAG's breakout A today. It sounds like we don't have consensus to make a recommendation about reducing use of partial in stable specs. It seems like we agree it would be good to have better tooling for cross-linking partials. 

ReSpec always links partials, and complains if it can't find the base. 

> But we probably don't want to be putting requests to tool authors in the design principles document since they're not applicable to the vast majority of the readers of the document.

Base on the above, I'm going to ahead and close this issue.

**Comment by dbaron** [comment]
I think the important bit of cross-linking partials is linking *from* the base *to* all the places that extend it with `partial`.  Does ReSpec do that?

**Comment by marcoscaceres** [comment]
> I think the important bit of cross-linking partials is linking from the base to all the places that extend it with partial. Does ReSpec do that?

No. That would be neat though (though I'm still a bit worried about things getting out of sync on static snapshots). 

However, we would need to get agreement on what that would look like in both ReSpec, Bikeshed, and any other tool (watsi or whatever the HTML one is called?)....  Should we reopen the TAG issue?
