### ISSUE TITLE
Checks for privacy and security sections don't work if lang is set to en-US

### ISSUE THREAD

**Issue by jnurthen** [w3c/respec#4156]
## Description of problem

Checks for privacy and security sections don't work if lang is set to en-US. Changing the Document language to en correctly shows the warnings but having the lang set to en-US does not.

Document languages are recommended to be as specific as possible to en-US is correct.

**URL to affected spec or repo:**

https://w3c.github.io/aria/

**What happened (e.g., it crashed)?:**

Gives console warning Missing localization strings for en-US.

**Expected behavior (e.g., it shouldn't crash):**

Should complain about no separate security / privacy sections

**Comment by xfq** [comment]
The reason may be because [ReSpecs's language matching method](https://github.com/w3c/respec/blob/471d6f5b20aab17e0b9db969418ef53f4b568d4c/src/core/utils.js#L176-L208) is relatively simple. Ideally, the algorithm in [BCP 47](https://www.rfc-editor.org/info/bcp47) should be used.

See https://github.com/wooorm/bcp-47-match for an example.
