### ISSUE TITLE
Double definition of term when data-lt is used

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#470]
when using `data-lt`, ReSpec should grab the text content from the <dfn> and use that as the first item in the `data-lt. Otherwise, you end up with,  E.g.,:

```HTML
<dfn data-lt="installed|installing">installed</dfn>
```

**Comment by marcoscaceres** [comment]
Fixed example of issue.

**Comment by halindrome** [comment]
I considered this.  However, I imagined a situation where the content of the dfn isn't actually one of the terms that I want people to be able to use to reference it.

    <dfn data-lt="term1|term2|term3">A long description of term1</dfn>

**Comment by marcoscaceres** [comment]
Most of my spec issues were related to this tho :(

**Comment by andreastt** [comment]
@halindrome The common case _is_ that the definition’s text content is the term people will want to reference it by though.  There might be cases where this is not the case, but it’s almost guaranteed that no additional harm will be done by using that definition’s text content as an additional reference term.

Since also specifications already rely on the implicit reference term in `<dfn>default reference term</dfn>`, it seems that this change will break a lot of specifications needlessly.

**Comment by halindrome** [comment]
Wait. What change?  That still works like it always did.

**Comment by halindrome** [comment]
If we implement this, in order to be compatible with the contract with
Shepherd, we should add the text contents to the data-lt attribute so that
term is explicitly one of the alternatives.

On Sat, Aug 1, 2015 at 9:04 AM, Shane McCarron <halindrome@gmail.com> wrote:

> Wait. What change?  That still works like it always did.
> On Aug 1, 2015 7:05 AM, "Andreas Tolfsen" <notifications@github.com>
> wrote:
>
>> @halindrome <https://github.com/halindrome> The common case *is* that
>> the definition’s text content is the term people will want to reference it
>> by though. There might be cases where this is not the case, but it’s almost
>> guaranteed that no additional harm will be done by using that definition’s
>> text content as an additional reference term.
>>
>> Since also specifications already rely on the implicit reference term in <dfn>default
>> reference term</dfn>, it seems that this change will break a lot of
>> specifications needlessly.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/w3c/respec/issues/470#issuecomment-126907408>.
>>
>


-- 
Shane McCarron
halindrome@gmail.com

**Comment by halindrome** [comment]
Never mind - I see you dd that!

**Comment by darobin** [comment]
+1 on this. Any reason this issue is still open?

**Comment by inexorabletash** [comment]
Hrm. This seems like it will require intrusively rewording specs in a common case:

```html
A <a>foo</a> has a <dfn data-lt="foo name">name</dfn>.

...

A <a>bar</a> has a <dfn data-lt="bar name">name</dfn>.
```

This now results in an error that "name" has duplicate definitions.

**Comment by inexorabletash** [comment]
This also seems to be generating duplicate definition errors for "contiguous IDL" usage, though I haven't dug into the precise reason. See http://w3c.github.io/IndexedDB/ for examples.

**Comment by marcoscaceres** [comment]
Naming things the same thing as other things doesn't seem great. I'm still not sure what the right solution is here. It seems to me that:

````
A <a>bar</a> has a <dfn>bar name</dfn>.
```

Would be the right thing to do, as that's how it's referenced elsewhere.

**Comment by inexorabletash** [comment]
I suppose it may be just my ED, which ends up with **database name**, **object store name**, **object store handle name**, **index name** and **index handle name**, which can be more conveniently referenced in prose as *foo*'s **name**, rather than *foo*'s **foo name** (and similar for *foo*'s **connection** or *foo*'s **transaction**). 

Anyway, we can ponder - it's fixable on my end. (The "contiguous IDL" issue seems more serious.)

**Comment by marcoscaceres** [comment]
@inexorabletash, I wonder if you can reference those by id.... need to try this out, but something like:

```HTML
A <a>foo</a> has a <dfn data-lt="foo name" id="foo-name">name</dfn>.
... 
Let <var>foo's</var> <a id="#foo-name">name</a> be whatever...
```

**Comment by marcoscaceres** [comment]
@inexorabletash re: contiguous IDL, we merged a patch last Friday that should fix that. If still busted, let me know.

**Comment by inexorabletash** [comment]
@marcoscaceres re: contiguous IDL: seems to still be busted, see: https://w3c.github.io/IndexedDB/

(67 errors, 45 of which are auto-generated definitions c/o IDL)

**Comment by marcoscaceres** [comment]
@inexorabletash ok, will take a look a bit later today.

**Comment by inexorabletash** [comment]
Thanks!

Re:
```html
A <a>foo</a> has a <dfn data-lt="foo name" id="foo-name">name</dfn>.
```
This would still complain if `name` was used elsewhere, since both 'name' and 'foo name' will be used as definitions. The linking's not the problem since unique definitions are specified.

I hate to suggest it, but maybe a `data-lt-noDefault` attribute that suppresses the use of the text content as the default term? (Or anything better, really.)

(I was peeking at the Fetch standard to see if I was being particularly weird, and it uses e.g. __header list__ and __body__ as the names of concepts as well as the names of properties of both request and response concepts)

**Comment by inexorabletash** [comment]
Filed #480 to track the contiguous IDL issue

**Comment by marcoscaceres** [comment]
@inexorabletash, sorry for the delay. I did what you suggested and added "data-lt-noDefault". Please take a look: 
https://github.com/w3c/respec/pull/481

**Comment by inexorabletash** [comment]
Cool, thanks. I updated IndexedDB testing against a local copy of respec and it works as expected.
