### ISSUE TITLE
In IDL sections, Promise-based API definitions run off the page

### ISSUE THREAD

**Issue by vijaybh** [w3c/respec#521]
In a pre class="idl" section of a Respec doc, try the following:

interface myInterface {
Promise < myReturnType > testFunction (
   DOMString parameter1,
   DOMString parameter2,
   DOMString parameter3,
   DOMString parameter4,
   DOMString parameter5,
   DOMString parameter6);
};

You'll see that instead of breaking across lines, the method definition scrolls off the page to the right. When printing (to PDF, for example) this will cause the text to be truncated in the output.

**Comment by plehegar** [comment]
we have a similar issue with callbacks. See 
http://w3c.github.io/performance-timeline/#idl-def-performanceobservercallback

**Comment by dontcallmedom** [comment]
a simple fix would be to add `white-space: pre-wrap` to the `pre.idl` rule in the stylesheet. can you see if that would work for you locally before I produce a patch in that direction?

**Comment by plehegar** [comment]
it does, but it's certainly not ideal since you don't control the formatting. I get this:

[Exposed=(Window,Worker)]
interface PerformanceObserverEntryList {
    PerformanceEntryList getEntries(optional PerformanceEntryFilterOptions filter);
    PerformanceEntryList getEntriesByType(DOMString type);
    PerformanceEntryList getEntriesByName(DOMString name, optional DOMString type);
};

callback PerformanceObserverCallback = void (PerformanceObserverEntryList entries, PerformanceObserver observer);

[Constructor(PerformanceObserverCallback callback),
 Exposed=(Window,Worker)]
interface PerformanceObserver {
    void observe(PerformanceObserverInit options);
    void disconnect();
};


Now, speaking to some of the webperf folks yesterday, folks might prefer the scrollbar rather than the uncontrolled line break.

**Comment by vijaybh** [comment]
I would echo that. I tried:
1. Adding white-space: pre-wrap to pre.idl
2. Adding overflow: auto to pre.idl
3. Combining 1 and 2

All the pre-wrap versions were a bit ugly - you get lines broken between a parameter's type and name, second and subsequent lines are not indented to the same level as the method name, and so on. On the screen, the scrollbar seemed the least evil. But when I print, the line still gets truncated and the scroll bar shows up in the output.

I think what a human would be going for in this situation may be to have each parameter on its own line, and maybe wrap if a single parameter's definition was too long. Another option might be to style differently for screen and print output.
