### ISSUE TITLE
Exampe yellow bar applied twice

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#583]
The yellow bar of examples is being applied twice.
 
![screenshot 2016-03-02 13 14 33](https://cloud.githubusercontent.com/assets/870154/13448655/dbd660c0-e078-11e5-8712-605f65adea5d.png)

**Comment by halindrome** [comment]
This only happens if your markup is weird... but I don't remember under
what circumstance.  Like multiple class="example" or something.

On Tue, Mar 1, 2016 at 8:15 PM, Marcos Caceres <notifications@github.com>
wrote:

> The yellow bar of examples is being applied twice.
>
> [image: screenshot 2016-03-02 13 14 33]
> <https://cloud.githubusercontent.com/assets/870154/13448655/dbd660c0-e078-11e5-8712-605f65adea5d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/583>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by tidoust** [comment]
I don't see anything weird with the markup. The bug occurs whenever there is a `<pre class="example">...</pre>` section in the source file.

ReSpec transforms that section into an outer `<div>` and an inner `<pre>`. The `example` class is added to both tags, which triggers the issue (the new stylesheet uses that class to create the left yellow bar). Dropping the inner `example` class solves the issue. I do not know if that can have other side effects.

I see code in examples.js that does just that... provided that the `useExperimentalStyles` flag is set:
https://github.com/w3c/respec/blob/develop/js/core/examples.js#L61

Shouldn't the check be dropped so that the code runs in all cases, now?

PS: note there are other parts of the code that refer to `useExperimentalStyles` (in issues-notes.js, structure.js, webidl-contiguous.js, aria.js). Shouldn't they be updated as well? Or are there new experimental styles already?

**Comment by halindrome** [comment]
My PR #588 fixes all of these.  BUt we are having build / integration
problems right now.  Soon.

On Wed, Mar 2, 2016 at 8:05 AM, François Daoust <notifications@github.com>
wrote:

> I don't see anything weird with the markup. The bug occurs whenever there
> is a <pre class="example">...</pre> section in the source file.
>
> ReSpec transforms that section into an outer <div> and an inner <pre>.
> The example class is added to both tags, which triggers the issue (the
> new stylesheet uses that class to create the left yellow bar). Dropping the
> inner example class solves the issue. I do not know if that can have
> other side effects.
>
> I see code in examples.js that does just that... provided that the
> useExperimentalStyles flag is set:
> https://github.com/w3c/respec/blob/develop/js/core/examples.js#L61
>
> Shouldn't the check be dropped so that the code runs in all cases, now?
>
> PS: note there are other parts of the code that refer to
> useExperimentalStyles (in issues-notes.js, structure.js,
> webidl-contiguous.js, aria.js). Shouldn't they be updated as well? Or are
> there new experimental styles already?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/issues/583#issuecomment-191249281>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
this was fixed in release 3.2.100 ish...
