### ISSUE TITLE
Determine dependencies prior to test / build

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#627]
There should be an automatic step where the system determines if the node modules required are installed and up to date.   Travis is (of course) doing this as a matter of course because it builds an environment from scratch, but since things change all the time an 'npm test' or 'npm build' (which doesn't actually exist) should have a pre-step where it does an 'npm install' or whatever makes sense.

**Comment by marcoscaceres** [comment]
Can do this easily, but would need you (and other maintainers) to add a couple of git-hooks (in your .git dir).

**Comment by halindrome** [comment]
Hmm.  Like what?  Couldn't the test script just do an 'npm install' ?

**Comment by marcoscaceres** [comment]
No, because it could break things. Note that TravisCI is also not just testing latest versions (just the versions it is given).

What I would like is 1 of:

1. When you check out "develop", it warns you if any deps are outdated.
2. When you try to release, it warns you that deps are outdated.
3. If out dated, it makes a new branch and updates everything, runs "npm test", and auto sends a PR. 

WDYT?

**Comment by halindrome** [comment]
Feels sexy.  Why not?

**Comment by marcoscaceres** [comment]
I went with a different option here: https://greenkeeper.io

We should start receiving PRs from greenkeeper in the next few hours.

**Comment by marcoscaceres** [comment]
See :heart_eyes:: https://github.com/w3c/respec/pull/676
