### ISSUE TITLE
Stop using bleeding edge features - please

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#722]
I get that the newest, coolest things are fun.  But they are not ubiquitous.  This latest problem with lack of support for something in IE is just embarrassing.

**Comment by marcoscaceres** [comment]
> On 29 Apr 2016, at 1:23 AM, Shane McCarron <notifications@github.com> wrote:
> 
> I get that the newest, coolest things are fun. But they are not ubiquitous. This latest problem with lack of support for something in IE is just embarrassing.
> 
Hardly embarrassing (and it's not IE, it's Edge) - I test all features on as many browsers as possible and constraint new features as much as possible (e.g., use "var" because of Safari). Problem is not with new features, it's that it's hard to test Edge via Travis or locally. 

So, the constructive thing to do is to figure out how we can test on Edge. Their might be an npm module that spins up a vm.
