### ISSUE TITLE
Figure out how to test in Edge

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#723]
Turns out people view specs in Edge (who would have thought, right?😝). We should figure out how to run our tests in it as part of CI.

**Comment by marcoscaceres** [comment]
Possible solution: https://www.appveyor.com

**Comment by marcoscaceres** [comment]
Example setup: https://github.com/ariya/karma-appveyor/blob/master/appveyor.yml

**Comment by marcoscaceres** [comment]
So, there is currently no Karma launcher for Edge... one has been in the works for a while tho:
https://github.com/nicolasmccurdy/karma-edge-launcher

I'm going to see if I can help with that in some way.

**Comment by marcoscaceres** [comment]
Waiting on https://github.com/nicolasmccurdy/karma-edge-launcher/issues/14

**Comment by travisleithead** [comment]
@thejohnjansen in case he has any insights here for getting Edge to work with CI

**Comment by marcoscaceres** [comment]
@thejohnjansen, you should take a look at nicolasmccurdy/karma-edge-launcher#14 - coordinating with folks from Microsoft there. Any help would be greatly appreciated (and a huge win for both Edge and Web Devs in general, IMHO)!

**Comment by nicolasmccurdy** [comment]
This is also still waiting on getting appveyor to support the version of Windows Server that includes Edge, right?

**Comment by nickmccurdy** [comment]
@marcoscaceres I have some pre-1.0 versions of `karma-edge-launcher` on npm that I'm interested in testing with this project (assuming that Appveyor lets us). Would you be interested in helping me with this? So far I'm trying to port the `copydeps.sh` build script to Node so it's easier to run on Windows, then maybe we could get a patch out to `detectBrowsers` that will support Edge with my launcher.

**Comment by marcoscaceres** [comment]
@nickevansuk, absolutely! Happy to help. Like you mentioned, the first thing would be to get confirmation from Appveyor that we can spin up Edge. 

If you haven't already finished the conversion of `copydeps.sh` - I'm happy to do it.. should take me only a few mins.

**Comment by marcoscaceres** [comment]
@nickevansuk, filed issue about the copydeps.sh script: https://github.com/w3c/respec/issues/954 

Let me know how you want to proceed.

**Comment by nickmccurdy** [comment]
I forget about the status with Appveyor, should we send them a message? As for the script, I got stuck with fixing some bugs with my port so it would help if you can do it. Node's built in `fs` library doesn't have a file copying method and the library is a bit more strict and minimal than the `cp` and `mv` commands, so there are more edge cases to deal with. I also started a [`windows_testing` branch on my fork](https://github.com/nickmccurdy/respec/tree/windows_testing), so far I only fixed syntax issues in `package.json` scripts.

Also, you know it seems like you accidentally mentioned someone else (I might have confused you because I recently changed my GitHub username). Either way, I'm still subscribed to this issue.

**Comment by marcoscaceres** [comment]
Apologies for the misname ... tab complete error on my part :)   

> I forget about the status with Appveyor, should we send them a message? 

So, they were running some strange version of Windows (Windows Server something something), and I don't think it included Edge. So yeah, I'll ping them again on twitter and get confirmation. 

Also, no probs about rewriting copydeps.sh. I'll take a look and hopefully it will just work in Windows.

**Comment by marcoscaceres** [comment]
Messaged the Appveyor folks: https://twitter.com/marcosc/status/792994572003516416

**Comment by nickmccurdy** [comment]
> Edge is available on Windows 10 only https://technet.microsoft.com/en-us/itpro/microsoft-edge/hardware-and-software-requirements

Since Microsoft's article mentions that Server 2016 doesn't have Edge, it seems like most Windows CI solutions wouldn't have it either. However, Edge could be manually tested on Windows systems (assuming the `npm install` would support Windows) through karma-detect-browsers (after it's patched to find Edge).

I'm new to both Appveyor and this project so I'm not sure if you are already using it for other things, but it seems to me like it might be useful to ensure that development installs at least complete on Windows. There could also be headless browser testing on Windows as a basic smoke test if there can't be any other browsers on Appveyor.

**Comment by nickmccurdy** [comment]
Hm, I just noticed that `Sauce supports Edge 13 and 14` (scroll down to Windows 10), so maybe it could be used for Windows browsing support instead of Appveyor (free for open source projects too). There's also [karma-sauce-launcher](https://github.com/karma-runner/karma-sauce-launcher).

**Comment by marcoscaceres** [comment]
> I'm new to both Appveyor and this project so I'm not sure if you are already using it for other things, but it seems to me like it might be useful to ensure that development installs at least complete on Windows. There could also be headless browser testing on Windows as a basic smoke test if there can't be any other browsers on Appveyor.

I thought it was a good solution till I learned that they don't have Edge. 

> Hm, I just noticed that Sauce supports Edge 13 and 14 (scroll down to Windows 10), so maybe it could be used for Windows browsing support instead of Appveyor (free for open source projects too). There's also karma-sauce-launcher.

Yeah, should switch to sauce labs. Just need to find time.

**Comment by nickmccurdy** [comment]
https://github.com/nickmccurdy/karma-edge-launcher/issues/34

**Comment by marcoscaceres** [comment]
I guess it's time to try SouceLabs.

**Comment by marcoscaceres** [comment]
won't  fix.
