### ISSUE TITLE
Drop promise poly

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#751]
It seems that the [target install base](http://caniuse.com/#search=Promise) no longer needs the promise poly. We should remove it.

**Comment by halindrome** [comment]
I know I sound like a broken record but... why would we remove something that 1) costs us nothing to use and 2) ensures that the product works for a wider range of people?

Maybe we should have a discussion at a W3C management / AC level about what the target audience is for W3C specifications in source form.

**Comment by marcoscaceres** [comment]
> On 12 May 2016, at 12:30 AM, Shane McCarron <notifications@github.com> wrote:
> 
> I know I sound like a broken record but... why would we remove something that 1) costs us nothing to use and
> 

This is not true. The inclusion and presence of any code is a cost (maintenance, bugs, kilobytes, etc). The only code that costs nothing is no code. Ideally, you want only enough code for the software to serve users. 

> 2) ensures that the product works for a wider range of people?
> 

By that measure, we would polyfill "all the things" just in case. There needs to be a reasonable cut off (e.g., 1 year support across browsers - and +75% global usage). I can double check, but I think we are long past that with promises. 

> Maybe we should have a discussion at a W3C management / AC level about what the target audience is for W3C specifications in source form.
> 

That seems not great: opinions(TM) of the AC don't really matter. Reliable data does matter tho: hence the link to caniuse.com that shows that the feature is widely enough supported that users would not be adversely affected by dropping it. 

I'm happy to agree on some timeline for dropping polyfills tho - but we should have a reasonable policy in place. At some point, polyfills like the promise one will no longer be maintained and will just be useless cruft that's not needed: I'm arguing that that is now - but we could be more conservative.

**Comment by halindrome** [comment]
> This is not true. The inclusion and presence of any code is a cost (maintenance, bugs, kilobytes, etc). The only code that costs nothing is no code. Ideally, you want only enough code for the software to serve users.

Of course.  I just meant that in terms of maintenance code such as this (a polyfill that is stable and rarely invoked) has little impact on our efforts at maintaining the code base AND, to the extent that we are using Promises, means that people who still have some ancient user agent will be able to view a spec that would otherwise fail to render.

I am not opposed to establishing a deprecation and removal policy.  The problem with maintaining a tool like ReSpec is that we have literally no idea how it is being used.  So we need to be very very careful when we start removing support for things that could still be in use.  

With regard to this particular polyfill... I don't have enough data to make a reasonable guess about what would happen if we removed it.  If you want to rip it out - go ahead.  If people complain that everything starts failing for their readers, we can always put it back.

As an aside, it would be super interesting to get some data about what specs are using ReSpec, and what user agents are processing the specs.   I wonder if we could include an opt-in phone home feature that would feed us some data about usage and then set a cookie (so it didn't do it again for the same spec for that user in that user agent).
