### ISSUE TITLE
Better handling for when specref goes down

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#828]
Spec ref went down again today and it's causing an unhandled exception to be thrown. Need better error recovery.

**Comment by marcoscaceres** [comment]
So, looking at the problem, the strategy would be to take the requested entries and make a bunch of place holders. 

The exception is actually being caught and reported correctly, and the biblio module is working correctly - but effectively, no references section is being added to the spec.

**Comment by halindrome** [comment]
I like that solution.  An easier one might be to insert the section with
text that talks about the exception.

My concern is a document production cycle where specref falls down and we
don't notice because there aren't any broken links.    If there are [XXX]
items in the document that dont resolve we generate warnings... which is
okay.  But we don't actually set the links, right?  So the pubrules checker
won't notice the broken links (because there aren't any) and we could push
something to TR with no references section.  Yikes!

On Wed, Jun 15, 2016 at 6:58 AM, Marcos Cáceres <notifications@github.com>
wrote:

> So, looking at the problem, the strategy would be to take the requested
> entries and make a bunch of place holders.
>
> The exception is actually being caught and reported correctly, and the
> biblio module is working correctly - but effectively, no references section
> is being added to the spec.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/w3c/respec/issues/828#issuecomment-226166191>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAfx8JSGE8FTR3boflTFUVWuWe0dACxjks5qL-jRgaJpZM4I2RhF>
> .
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
Would definitely continue to emit an error, so would abort spec generation.

**Comment by marcoscaceres** [comment]
Closed via https://github.com/w3c/respec/issues/828
