### ISSUE TITLE
Use working group ID to generate patent link

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec#915]
It would be nice to not have to put in a your rail for the patent link, but instead just putting the magic number given by the W3C.

**Comment by sidvishnoi** [comment]
Would it be better (and possible) to provide just the `wgURI` and infer `wg` and `wgPatentURI` from it? I think it's easier to remember the group URI instead of group number.
We may perhaps scrape (or create a tiny database from) this https://www.w3.org/2004/01/pp-impl/#groups to get group details. This may be done as a part of #683.

**Comment by dontcallmedom** [comment]
a better way than scraping would be to use the [W3C API](https://api.w3.org/doc) to that effect (probably to slurp the data every so often, rather than directly from in the browser)

**Comment by sidvishnoi** [comment]
Closed via https://github.com/w3c/respec/pull/2969
