### ISSUE TITLE
Warn when IDL members don't have a dfn

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#935]
(this came up at TPAC lunch)

ReSpec makes it easy to create IDL, but does not encourage authors to ensure there are prose descriptions for all of the various IDL things declared.  There should be warnings if, in particular, IDL definitions are not referenced (outside of IDL blocks).

**Comment by marcoscaceres** [comment]
Good suggestion.

**Comment by halindrome** [comment]
I mentioned this in the ARIA working group meeting today and they LOVE the idea.  One of their big complaints about some specs is that there is no way to tell what the WebIDL really DOES.

**Comment by halindrome** [comment]
Janina mentioned that the W3C I18N groups may also have concerns in this area.  Do you have any comments @r12a ?

**Comment by r12a** [comment]
Summary descriptions of grammars and algorithms are indeed very helpful to i18n folks when doing reviews, since it can be hard to find the time to plough through algorithms to figure out what they mean, and frustrating if it's actually something simple that could have been explained with a very short side text. (cc @aphillips)
